# Site settings
baseurl = "https://diencothanhhien.netlify.com/"
languageCode = "vi-vn"
title = "Điện cơ Thanh Hiền"
theme = "hugo-ecommerce-theme"
defaultContentLanguage = "vi"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-149344138-1"
paginate = 8
disableLanguages = ["en"]

##########################################
[Languages]
#Vietnamese
[Languages.vi]
title = "Điện cơ Thanh Hiền"
weight = 0

[Languages.vi.permalinks]
product = "/san-pham/:slug"

[[Languages.vi.menu.main]]
url    = "#"
name   = "Bài viết"
weight = 1
identifier = "blog"
[[Languages.vi.menu.main]]
url    = "/blog"
name   = "Sản phẩm mới"
weight = 1
parent = "blog"
[[Languages.vi.menu.main]]
url    = "/dala-kitchen"
name   = "Hướng dẫn"
weight = 2
parent = "blog"

[[Languages.vi.menu.main]]
url    = "/san-pham"
name   = "Sản Phẩm"
weight = 2

[[Languages.vi.menu.main]]
url    = "/qa"
name   = "Hỏi Đáp"
weight = 3

[[Languages.vi.menu.main]]
url    = "#"
name   = "Về ĐCTH"
weight = 4
identifier = "ve-dalafarm"
[[Languages.vi.menu.main]]
url    = "/company-profile"
name   = "Đôi nét về ĐCTH"
weight = 1
parent = "ve-dalafarm"
[[Languages.vi.menu.main]]
url    = "/company-docs"
name   = "Giấy tờ chứng nhận"
weight = 2
parent = "ve-dalafarm"
[[Languages.vi.menu.main]]
url    = "/team"
name   = "Thành Viên ĐCTH"
weight = 3
parent = "ve-dalafarm"
[[Languages.vi.menu.main]]
url    = "/#contact"
name   = "Liên Hệ"
weight = 5

## English
[Languages.en]
title = "Thanh Hien Electromechanical"
weight = 0

[Languages.en.permalinks]
product = "/product/:slug"

[[Languages.en.menu.main]]
url    = "#"
name   = "Blog"
weight = 1
identifier = "blog"
[[Languages.en.menu.main]]
url    = "/blog"
name   = "New product"
weight = 1
parent = "blog"
[[Languages.en.menu.main]]
url    = "/dala-kitchen"
name   = "Guides"
weight = 2
parent = "blog"

[[Languages.en.menu.main]]
url    = "/product"
name   = "Products"
weight = 2

[[Languages.en.menu.main]]
url    = "/qa"
name   = "FAQ"
weight = 3

[[Languages.en.menu.main]]
url    = "#"
name   = "About Us"
weight = 4
identifier = "about-us"
[[Languages.en.menu.main]]
url    = "/#about-us"
name   = "Thanh Hien Electromechanical Journey"
weight = 1
parent = "about-us"
[[Languages.en.menu.main]]
url    = "/company-profile"
name   = "Profile"
weight = 2
parent = "about-us"
[[Languages.en.menu.main]]
url    = "/company-docs"
name   = "Certificates"
weight = 3
parent = "about-us"
[[Languages.en.menu.main]]
url    = "/team"
name   = "Thanh Hien Electromechanical Team"
weight = 4
parent = "about-us"


[[Languages.en.menu.main]]
url    = "/#contact"
name   = "Contact"
weight = 5

[params]
  dateform        = "January 2, 2006"
  dateformShort   = "January 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  # enableLanguageSwitchingButton = true

  # Metadata mostly used in document's head
  # description = ""
  # themeColor = "#494f5c"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = true  # Set "text-align: justify" to `.content`.

  relatedPosts = true  # Add a related content section to all single posts page
